### ISSUE TITLE
wix-storybook-utils - testkit generator issues

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-ui#1220]
In some cases (i don't know how to distinguish them from others):
1. The properites are created with a prefix of "driver."
![image](https://user-images.githubusercontent.com/7388217/55379661-744f8f00-5526-11e9-8777-7362697fcc5f.png)

2. A protractor driver exists but documentation is not generated for it.

How to reproduce?
In MultiSelect storybook i replaced the generated docs with a manual one,
so you should replace it back to this:
`
      tab({
        title: 'Testkit',
        sections: [testkit()],
      }),
`

**Comment by argshook** [comment]
> In some cases (i don't know how to distinguish them from others):
> The properites are created with a prefix of "driver."

for testkits that have nested objects, each nested property is displayed
in a separate table with namespace.

For example, given testkit:

```js
export testkit = () => {
  const driver = { click, exists };
  const inputDriver = { click, exists };

  return {
    driver,
    inputDriver,
    click,
    exists
  }
}
```

the resulting output would be three tables:

1. one with `driver.click` and `driver.exists`
2. one with `inputDriver.click` and `inputDriver.exists`
3. one with just `click` and `exists`

sometimes, say, `inputDriver` is output of `require`d function from
other file, maybe transpilled in node_modules, with or without some
parameters, maybe proxied through another `require` (maybe not), etc.
The more complex the testkit, the harded it is to parse it.

If parser fails to parse it, it will not be displayed in the storybook.

Hence, there can be situation where testkit parsing succeded to parse
`driver` part but failed `inputDriver`. Output shows only one table and
it's full of just `driver.` namespace.

Ultimate solution is to make parser not only read source code as string
(to extract comments) but also evaluate it (to extract data like described above)

until ultimate solution is reality (if ever), we have our best shot :)

---

> A protractor driver exists but documentation is not generated for it.

this is fixed since https://github.com/wix/wix-style-react/pull/4417

---

sorry for wall of text, i have two keyboards
