### ISSUE TITLE
wix-storybook-utils: AutoExample issues

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#309]
This Issue is suppose to gather all the encountered issue with using the AutoExample, so we can have a discussion about it.

General / Methodology:
---------
- `<AutoExample>` is used for testing. I this the right approach? 
  - The alternative is to have a test page or pages (hidden story/stories) with manual examples for testing only. 
    - This allows total freedom for setting up the tested component and it's surrounding components if needed.
    - The makes the test isolated without any <AutoExample> code which is not needed for testing.
    - This allows for making eyes snapshots which include many variation in one page, which is easier to review in applitools.
    - The only "cons" is that in order to test many variations (different props), you can not use the `AutoExampleDriver.setProps()`, and you need to render each variation separately in the story (instead of in the test). And if you need the tested component to be the only component on the page, then you would have to reload the page (different story for each test case), and thus the test will be slower.
- Auto-Story uses `componentProps: (setState, getState)=> {props}` property for the `AutoExample` to work.
  - is a new API to learn. Adds learning curve as opposed to writing a normal React component which renders the <AutoExample>

UseCases
----------
 - Look at [Range](https://wix.github.io/wix-style-react/?selectedKind=3.%20Inputs&selectedStory=3.7%20Range&full=0&addons=0&stories=1&panelRight=0): It needs to be passed a <Label> and 2 <Input> component to actually do something. The example in the storybook is good. Should the AutoExample's component be the RangeExampleComponent?
 - Manual example with Raw code - Example with raw code use the `raw-loader`, and the auto-docs don't work because it doesn't use the loader.

Specific Issues / Bugs:
----------
 - componentProps:
   - passing children as an array, adds `eslint` warning that `key` prop needs to be added.
   - (`setProps`, `getProps`): can not call only `getProps` not within `getProps`
   - Some test need to wrap the <AutoExample>. Like focus test which needs to reset the focus to a wrapping div.
 - examples:
   - Manual example with Raw code - auto-docs don't work because it doesn't use the raw-loader.

**Comment by argshook** [comment]
> `<AutoExample>` is used for testing. I this the right approach?

it's probably not. the idea was to reduce the amount of code because of repetitive components and reuse mechanism of autoexample. it works really well for simple components but for anything more complex i need to hack. i tried few "automated" approaches until autoexampledriver became what it is today. all sucked and looks like autoexampledriver sucks too. Maybe you have some idea but i guess we just have to do components for e2e manually.

also, i think we need to separate documentation and e2e. currently we have small express server to serve `storybook-static`. maybe it should serve manually tailored pages for each component

---

> Auto-Story uses `componentProps: (setState, getState)=> void`

it's not `void`, it's an object which goes to `<YourComponent {...here}/>`.

autodocs renders component, connects its props to controls in storybook and shows interactive code example. without something like `componentProps` you're left to create your own reusable mechanism or do everything manually.

autodocs was made to prevent you from doing it manually. we can choose to:
* use/improve autodocs
* use/create something else
* go back to doing it all manually (i don't want it again)

---

> `(setProps, getProps)`: can not call only getProps not within getProps

i'll take a look again at this but i gotta say, when you `getProps` at the time of setting props, it's a chicken-egg situation. you may be trying to get a prop which is not set yet. and in that case, why use `getProps` at all.

---

> Manual example with Raw code - auto-docs don't work because it doesn't use the raw-loader.

please elaborate this one.


---

also, since this is a wall of text, i suppose it'd be better to open separate issue for specific details on something

**Comment by shlomitc** [comment]
* I think that it's good to use the autodocs both for documenting and testing since we only test the example and not the entire story. Having different documentation and testing is tedious, requires more maintenance. I would like to know what can't be achieved in the current implementation, then we can discuss how to improve it.

* The only feature I miss is the ability to render the component with different props (testing the initial state of the component in E2E), but this can be achieved pretty easily I think.

* We can improve the documentation of the tool, in order to make it easier for people to use. this means a section about how to create a story and how to test using the tool.

* The `Range` component and composition went wrong, so it's a different discussion and not only related to the AutoDocs

* Regarding manual example, we should usually reduce it to the minimum and only if this is something we can't get from the AutoExample. So it's ok if we don't have a perfect solution for it now.

**Comment by argshook** [comment]
> The only feature I miss is the ability to render the component with different props (testing the initial state of the component in E2E), but this can be achieved pretty easily I think.

currently this is done by using `AutoExampleDriver`. but it's such a hack it's not even funny. You say it can be achieved easily, please tell me how, really don't know. i tried a few approaches ending up with autoexampledriver but i would like to get rid of it

**Comment by argshook** [comment]
most of issues written here are now split in separate issues.
as for testing, we decided to not use autodocs for complex e2e and simply write separate storypage from scratch in those cases
