### ISSUE TITLE
AutoDocs - Hot reload does not work when changing README.ms file

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#526]
by "Hot reload" I mean when running `npm run storybook`
See also this issue: #508 
since I think using README should be deprecated.

**Comment by argshook** [comment]
hot reload works with a quirk: you need to trigger file change in `.story.js` file for watchman to catch, rerun component parser and display updated content.
in essence, it's opening `.story.js` file and saving it (cmd+s).
it's a trade off, if parser were to run on every file change, it would take much longer for hot reload to finish. you don't want it to take long when working on tests, for example.

readme cannot be deprecated currently, because many components have readme.md files. unless we remove readmes everywhere, i see no reason to deprecate it.
