### ISSUE TITLE
AutoDocs - ExampleProps does not show preview of React.Element as label

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#599]
See Button story in WSR, see the prefixIcon exampleProps:
https://wix-wix-style-react.surge.sh/?selectedKind=5.%20Buttons&selectedStory=5.1%20Standard&full=0&addons=0&stories=1&panelRight=0

We used to have it show the actual icons.
Now we see only [object, Object]

**Comment by argshook** [comment]
thanks! **TL;DR;** the `[object Object]` happens on built storybook only and so i didn't notice it locally. It is because now i `toString` instead of rendering value

---
**longread**

previously i was rendering nodes in dropdown so we saw icons. this is nice for small components (like icons) but becomes problematic when node is something more complex (for example, something like Page.Content). Since i don't render node anymore and i want to make a searchable list, i simply `toString` value.

Of course not all values can work with `toString` and for this reason it's possible to configure `exampleProps` with `{label, value}` shape of object.
the problem here is that i can set some `value` but it would only be meaningful if it was the name of an icon. However, that name is gone once storybook is built, because all icons become anonymous functions.
a fix, like in many other cases, would be to include `displayName`, and this is what `svg2react-icon` can do. I'll PR that part.

**Comment by argshook** [comment]
done
