### ISSUE TITLE
wix-storybook-utils: extract copy to clipboard logic

### ISSUE THREAD

**Issue by yardnsm** [wix/wix-ui#832]
Currently, the "copy to clipboard" logic is coupled with both the `<CodeBlock/>` an the `<LiveCodeExample/>` (https://github.com/wix/wix-ui/pull/828) components.

It'll be nice to extract this logic to another component that will handle the copying and the notification display.

**Comment by argshook** [comment]
not sure we need dedicated component for that since we use 3rd party for copy-paste and it's
trivial to use:

```js
import copy from 'copy-to-clipboard';
copy('some text')
```

regarding notification: wix-storybook-utils no longer has wix-style-react dependency and so no
`<Notification/>` component, unless we create (or copypasta) one

let's make one if copypaste becomes a repeated pattern but as of now it's used only in two places
and is real easy to implement

closing for now.
